sudo: required

language: php
    - '7.0'

services:
    - docker

before_script:
    - composer create-project symfony/framework-standard-edition sf3_project
    - cp -r ./docker sf3_project
    - cd sf3_project/docker
    - sh ./docker.sh -d

script:
    - docker exec -u www-data -i sf_web composer require phpunit/phpunit
    - docker exec -u www-data -i sf_web vendor/phpunit/phpunit/phpunit
    - docker-compose stop
